version: "3"
services:
  maildev:
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "8080:8080"
    environment:
      MAILDEV_SMTP_PORT: 1025
      MAILDEV_WEB_PORT: 8080
      MAILDEV_OUTGOING_PASS: password
      MAILDEV_OUTGOING_USER: user
      MAILDEV_OUTGOING_HOST: localhost
      MAILDEV_INCOMING_PASS: password
      MAILDEV_INCOMING_USER: user
